### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by mytja** [raitonoberu/spotiyt-server#5]
Hello!
I modified this library:
[imgcompression.zip](https://github.com/raitonoberu/spotiyt-server/files/5145672/imgcompression.zip)
from this repository (https://github.com/saurabhgharat/image-compression) and I thought, it could be used in your project to compress images when downloading!
Do you think you can use it?
Thank you

**Comment by raitonoberu** [comment]
Hi @mytja!
I don't think that this library might be useful. All the work with images on the server is to send the link directly from Spotify. These images are already quite compressed.

**Comment by alexmercerind** [comment]
Hi @mytja!

It's great to know that you wanna contribute to this project. But this backend just uses the image URLs already given by the Spotify and sends those already existing URLs to the app.
In other words, the images used in rendering in the app are stored on Spotify's server and we aren't controlling their encoding etc. 
Spotify already generally gives us those images in three res. 64, 300 & 640. And they are already keeping it quite compressed. The only time we internally fetch any album art in this backend is when adding it to a track's metadata.
