### ISSUE TITLE
A little plan...

### ISSUE THREAD

**Issue by alexmercerind** [raitonoberu/spotiyt-server#6]
Hi @raitonoberu !

The API now is working great. But as we know, we are searching for music in Spotify & then searching the same track in YouTube (with lyrics) for downloading it using youtube-dl.

This method is very inaccurate & does not provide user the highest quality music & sometimes gives wrong music to the user aswell. 

Now what came up in my mind is that, since this whole backend is powered by YouTube's music, why don't I switch to YouTube Music for searching & downloading music.
But, obviously Google does not provide an API for YouTube music. So, a project recently showed up to me [ytmusicapi](https://github.com/sigma67/ytmusicapi). This seems really promising to me. Switching to this library will give us many benefits, like we will be able to provide actual music to the user (not the lyric videos), a better music library in searches etc.

I'm planning to do this separately for a while. I'll keep using this project for the time-being (or permanently, if I discover any problem).

**Comment by raitonoberu** [comment]
Hi @alexmercerind!

I agree with you, search results are not always correct. The library you mentioned is really impressive, it can help us deal with it. What about music quality... Even if we use YouTube Music, we will still have to use youtube-dl for downloading. Its best audio quality is 128 kbps AAC (we already use it).

Anyway, I'll try to do something with it on the weekends. <sub><sup>unfortunately, I don't have much time on weekdays because of school</sup></sub>

Thanks.

**Comment by raitonoberu** [comment]
Btw I wanted to suggest using the public Genius API to search for videos (pretty strange but its library is huge).
<details>

```python3
import requests

q = "Rick Astley - Never gonna give you up"

r = requests.get("https://genius.com/api/search", data={"q": q})
path = r.json()['response']['hits'][0]['result']['api_path']

r = requests.get("https://genius.com/api" + path)
print("youtube url:", r.json()['response']['song']['youtube_url'])
```
</details>
But your idea is much better, I didn't even think about it!

**Comment by alexmercerind** [comment]
Hi @raitonoberu,
Don't worry at all. You take care of your study & school. 😃
I'll do everything related to it. I'll take care.
I have already started doing stuff in a branch of this repo. (Haven't pushed it yet).
I wanted to share my future idea with you & consult a little.
Thanks a lot!
